include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unnecessary_type_check: ignore
    sort_constructors_first: ignore

linter:
  rules:
    public_member_api_docs: true
    prefer_single_quotes: true
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    cancel_subscriptions: true
    unawaited_futures: true
    avoid_print: false  # Allow in example
